#pragma once

#include "cpp_class.hpp"
#include <fmt/format.h>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

struct CppFile final
{
    std::vector<std::string> includes;
    std::vector<CppClass> classes;

    std::string render() const
    {
        std::string rendered;

        fmt::format_to(std::back_inserter(rendered), R"(// -----------------------------------------------------------------------------
// This file was automatically generated by YORM.
// 
// https://github.com/thelastjotun/yorm
// 
// DO NOT EDIT MANUALLY.
// -----------------------------------------------------------------------------

#pragma once

)");

        for (const auto &inc : includes) {
            fmt::format_to(std::back_inserter(rendered), "#include <{}>\n", inc);
        }
        fmt::format_to(std::back_inserter(rendered), "\n");

        for (const auto &cls : classes) {
            fmt::format_to(std::back_inserter(rendered), "{}", cls.render());
        }

        return rendered;
    }

    void save_to_disk(const std::string &filepath) const
    {
        std::ofstream out(filepath);
        if (out.is_open()) {
            out << render();
            std::cout << "Successfully saved to " << filepath << "\n";
        } else {
            std::cerr << "Failed to open file for writing: " << filepath << "\n";
        }
    }
};
